### ISSUE TITLE
用的好好的，换了一个新链接，报错

### ISSUE THREAD

**Issue by JianKingTeam** [maintell/webBenchmark#5]
./webBenchmark_linux_x64 -c 32 -s https://xxxx.com/2.jpg
nameserver 8.8.8.8:53 took 30.57944mspanic: interface conversion: dns.RR is *dns.CNAME, not *dns.A

goroutine 8 [running]:
main.nslookup(0x7fffe85057d4, 0x24, 0x7bee00, 0x7, 0x0, 0x0, 0x0)
	D:/D2/Code/webBenchmark/main.go:195 +0x58d
main.showStat()
	D:/D2/Code/webBenchmark/main.go:111 +0xf2
created by main.main
	D:/D2/Code/webBenchmark/main.go:279 +0x135

大佬，用的最新版v0.3， 用的好好的，刷了100多TB，换了一个新链接就不行了，什么原因？ 怎么解决呢？

目前换回v0.2版本 正常。

**Comment by simplove** [comment]
windows同样的问题
D:\>WebBenchmark.exe -c 64 -s https://xxx.xxx.xxx
nameserver 8.8.8.8:53 took 87.5225mspanic: interface conversion: dns.RR is *dns.
CNAME, not *dns.A

goroutine 6 [running]:
main.nslookup(0xc00000a188, 0xc, 0x7bde05, 0x7, 0x0, 0x0, 0x0)
        D:/D2/Code/webBenchmark/main.go:195 +0x5a5
main.showStat()
        D:/D2/Code/webBenchmark/main.go:111 +0x105
created by main.main
        D:/D2/Code/webBenchmark/main.go:279 +0x135

**Comment by tonyzhou777** [comment]
同样，0.2 没有 DNS 报错，0.3 因为增加了 - i 参数，DNS 如果是 cname 会报错

**Comment by maintell** [comment]
fixed

**Comment by tonyzhou777** [comment]
> fixed

请问该怎么使用？
